name: 'wait-for-checks'
description: 'Waits for checks on repository to complete'
author: 'Nicolas Trüssel'

# Define your inputs here.
inputs:
  token:
    description: >
      Access token for the GitHub API. Required to fetch the tags and commits in
      order to calculate the version number
    required: true
    default: ${{ github.token }}

# Define your outputs here.
outputs: {}

runs:
  using: node20
  main: dist/index.js
